#ifndef __ANIM_PLAYER_EFFECT_DEFINE_H__
#define __ANIM_PLAYER_EFFECT_DEFINE_H__
#include "cocos2d.h"
USING_NS_CC;

#define ANIM_PLAYER_EFFECT_NONE				0
#define ANIM_PLAYER_EFFECT_GARY				ANIM_PLAYER_EFFECT_NONE + 1
#define ANIM_PLAYER_EFFECT_GLOW				ANIM_PLAYER_EFFECT_GARY + 1
#define ANIM_PLAYER_EFFECT_ONE_COLOR		ANIM_PLAYER_EFFECT_GLOW + 1
#define ANIM_PLAYER_EFFECT_MUILT_COLOR		ANIM_PLAYER_EFFECT_ONE_COLOR + 1
#define ANIM_PLAYER_EFFECT_MUILT_COLOR_CCS  ANIM_PLAYER_EFFECT_MUILT_COLOR + 1
#define	ANIM_PLAYER_EFFECT_BLUR				ANIM_PLAYER_EFFECT_MUILT_COLOR_CCS + 1
#define	ANIM_PLAYER_EFFECT_SEJIE			ANIM_PLAYER_EFFECT_BLUR + 1
#define ANIM_PLAYER_EFFECT_WAVE				ANIM_PLAYER_EFFECT_SEJIE + 1
#define ANIM_PLAYER_EFFECT_HU_XI			ANIM_PLAYER_EFFECT_WAVE + 1
#define ANIM_PLAYER_EFFECT_SHUI_CAO			ANIM_PLAYER_EFFECT_HU_XI + 1
#define ANIM_PLAYER_EFFECT_BAIDONG			ANIM_PLAYER_EFFECT_SHUI_CAO + 1
#define ANIM_PLAYER_EFFECT_DENGBAIDONG		ANIM_PLAYER_EFFECT_BAIDONG + 1
#define ANIM_PLAYER_EFFECT_ACTORWAVECLIP	ANIM_PLAYER_EFFECT_DENGBAIDONG + 1
#define ANIM_PLAYER_EFFECT_SHUI_DOU_DONG	ANIM_PLAYER_EFFECT_ACTORWAVECLIP + 1
#define ANIM_PLAYER_EFFECT_BAOJI_SHADOW			ANIM_PLAYER_EFFECT_SHUI_DOU_DONG + 1
#define ANIM_PLAYER_EFFECT_GRASS_WAVE			ANIM_PLAYER_EFFECT_BAOJI_SHADOW + 1
#define ANIM_PLAYER_EFFECT_BRIGHT_BIAN			ANIM_PLAYER_EFFECT_GRASS_WAVE + 1
#define ANIM_PLAYER_EFFECT_HUE			ANIM_PLAYER_EFFECT_BRIGHT_BIAN + 1
#define ANIM_PLAYER_EFFECT_BIANSE			ANIM_PLAYER_EFFECT_HUE + 1
//#define ANIM_PLAYER_EFFECT_WATER_RIPPLE		0x10000000
#define ANIM_PLAYER_EFFECT_SANDBOX			ANIM_PLAYER_EFFECT_BIANSE + 1
#define ANIM_PLAYER_EFFECT_YUNPINGTAI			ANIM_PLAYER_EFFECT_SANDBOX + 1
#define ANIM_PLAYER_EFFECT_MAX				ANIM_PLAYER_EFFECT_YUNPINGTAI + 1

typedef struct {
	ccColor3B oneColorValue;
	ccColor4F DieJiaColorValue;
	float	  DieJiaCurAlpha;
	CCPoint	  GaussianBlurSize;
	float       BianSe_r;
	float       BianSe_g;
	float       BianSe_b;
	float       Hue;
	float	  	Sejie_min_in;
	float	  	Sejie_max_in;
	float	  	Sejie_inGamma;
	float	  	Sejie_min_out;
	float	  	Sejie_max_out;
	float	  	Wave_Random;
	float	  	Wave_Width;
	float		Wave_Freq;
	float		HuXi_Width;
	float		YunPingTai_Width;
	float		ShuiCao_Random;
	float		ShuiCao_WaveWidth;
	float		ShuiCao_Freq;
	float		BaiDong_Random;
	float		BaiDong_Freq;
	float		DengBaiDong_Random;
	float		DengBaiDong_Freq;
	float		BaoJiShadowAlpha;
} AnimEffectInfo;

#endif