#ifndef __GUI_CONFIG_H__
#define __GUI_CONFIG_H__
//
//#include "../../wrapper/wrapper.h"
//#include "../../Actor/Hero.h"
#include "../../utils/Utils.h"
//#include "../../CSystem/CSystem.h"
#include "../../defines.h"
#include "../../utils/TextManager.h"
//#include "../../Online/CmdSendManager.h"
//#include "../../Online/CMD/CmdMaker.h"
//#include "../../script/lua/luaWrapper.h"

#include "check_box/XCheckBox.h"
//#include "dialog/ConfirmDialog.h"
//#include "dialog/Dialog.h"
//#include "dialog/InputDialog.h"
//#include "marquee/XMarquee.h"
//#include "option/Option.h"
//#include "text/XText.h"
#include "util/XCCBReader.h"
//#include "util/XCCMenu.h"
//#include "util/XCCScrollViewPage.h"
//#include "util/XCCScrollViewBar.h"
//#include "tab/CCControlButtonTab.h"
//#include "tab/CCTab.h"
//#include "tab/CCMenuTab.h"
//#include "list/CCSecondList.h"
//#include "pack_base/PackBase.h"
//#include "../../soundManager/soundManager.h"
#endif // __GUI_CONFIG_H__